# Generated by Django 5.1.2 on 2024-11-12 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_description', models.TextField()),
                ('related_file', models.FileField(blank=True, null=True, upload_to='request_files/%y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='control.user')),
            ],
        ),
    ]
