# Generated by Django 5.1.2 on 2024-12-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
