# Generated by Django 5.1.2 on 2024-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_name']},
        ),
        migrations.AlterField(
            model_name='request',
            name='related_file',
            field=models.FileField(default='no', upload_to='request_files/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_year',
            field=models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year'), ('Graduated', 'Graduated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='templates/default.png', null=True, upload_to='profiles/%y/%m/%d'),
        ),
    ]
