# Generated by Django 5.1.2 on 2024-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_request_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='related_file',
            field=models.FileField(upload_to='request_files/%y/%m/%d'),
        ),
    ]
