# Generated by Django 5.1.2 on 2024-11-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_request_related_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profiles/24/11/default.png', null=True, upload_to='profiles/%y/%m/%d'),
        ),
    ]
