# Generated by Django 5.1.2 on 2024-11-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profiles/24/11/20/default.jpg', null=True, upload_to='profiles/%y/%m/%d'),
        ),
    ]
