# Generated by Django 5.1.2 on 2024-12-07 16:18

import control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345678', max_length=128, validators=[control.models.validate_password_length]),
        ),
    ]
